input:
  REGION: europe-west2
  PROJECT_ID: cpto-content-metadata
  MODEL_ID: 4804056572823076864
  MACHINE_TYPE: n1-standard-8
  BATCH_SIZE: 84
  MIN_NODES: 1    # minimum number of nodes (virtual machines)
  MAX_NODES: 4
  INPUT_FORMAT: bigquery
  OUTPUT_FORMAT: bigquery
  INPUT_TABLE_URI: bq://cpto-content-metadata.content_ner_daily_new.all_parts_of_page
  OUTPUT_TABLE_URI: bq://cpto-content-metadata.named_entities_raw_daily.all_parts_of_page
  BATCH_JOB_NAME: bq-request-ner-daily
  INCLUDED_FIELDS:
    - url
    - text
    - line_number
    - part_of_page
