# This file runs operations on GCP Cloud Build. Essentiall carries out steps that you may perform
# locally, but using Google Cloud Build instead. Crucially, the first step loads the NER model
# embedded into the image at build, rather than loading during app runtime.
# For more information, visit https://cloud.google.com/build/docs/build-config-file-schema.

steps:
# Download the model to embed into the images
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['-m', 'cp', '-r', 'gs://cpto-content-metadata/models/mdl_ner_trf_b1_b4', '.']
  id: 'download-model'
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/cpto-content-metadata/fastapi-ner-trf', '.']
  waitFor: ['download-model']
# Push container image to container registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/cpto-content-metadata/fastapi-ner-trf']

images:
- gcr.io/cpto-content-metadata/fastapi-ner-trf
