steps:
# Download the model to embed into the images:
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['-m', 'cp', '-r', 'gs://cpto-content-metadata/models/mdl_ner_trf_b1_b4', '.']
  id: 'download-model'
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/cpto-content-metadata/fastapi-ner-trf', '.']
  waitFor: ['download-model']
# Push container image to container registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/cpto-content-metadata/fastapi-ner-trf']

images:
- gcr.io/cpto-content-metadata/fastapi-ner-trf
