# Connect our Cloud service with GitHub, in such a way that, with each push,
# the Docker image is uploaded to the Artifact Registry of our Cloud service.

# Steps:
# - Deploy custom docker to Artifact Registry
# - Upload model to Vertex AI model registry
# Secrets are defined in GitHub secrets

name: GovNER Model API

on:
 push:
  paths:
    - fast_api_model_serving/**

env:
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}

jobs:
    setup-build-upload:

        # Authenticate to GCP
        name: Setup Gcloud Account
        runs-on: ubuntu-latest
        # Add "id-token" with the intended permissions.
        permissions:
          contents: 'read'
          id-token: 'write'
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v3
        - id: 'auth'
          uses: 'google-github-actions/auth@v1'
          with:
            workload_identity_provider: ${{ secrets.GCP_GITHUB_WORKLOAD_IDENTITY_PROVIDER }}
            service_account: ${{ secrets.GCP_NER_MODEL_API_SA }}
        # `setup-gcloud` automatically picks up authentication from `auth`
        - name: 'Set up gcloud'
          uses: 'google-github-actions/setup-gcloud@v1'

        # Allow CI/CD instance to use Docker in GCP
        - name: Configure Docker
          run: gcloud auth configure-docker --quiet

        # Run cloudbuild.yaml in the correct directory
        - name: Run Cloud Build Process
          run: gcloud builds submit --config cloudbuild.yaml
          working-directory: fast_api_model_serving

        # Upload model to Vertex AI model registry
        - name: Upload model to Vertex AI model registry
          run:  bash ${GITHUB_WORKSPACE}/fast_api_model_serving/deploy_to_vertexai.sh
