name: Deploy new-content NER inference workflow

on:
  push:
    paths:
      - inference_pipeline_new_content/daily_batchjob_workflow.yml

jobs:
    deploy-gcp-workflow:
        # Authenticate to GCP
        name: Setup Gcloud Account
        runs-on: ubuntu-latest
        steps:
        # Set GCP credentials in CI/CD instance
        - id: 'auth'
          uses: 'google-github-actions/auth@v1'
          with:
            credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
        - name: 'Set up Cloud SDK'
          uses: 'google-github-actions/setup-gcloud@v1'
        - name: Checkout Repository
          uses: actions/checkout@v3
        - name: Use gcloud CLI to deploy workflow
          run: |
            gcloud workflows deploy daily-ner-batch-predictions \
            --location europe-west2 \
            --source inference_pipeline_new_content/daily_batchjob_workflow.yml \
            --project ${{ secrets.GCP_PROJECT_ID }} \
            --labels "commit-sha=${{ github.sha }}" \
            --service-account cpto-content-metadata-sa@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com
