# Secrets defined in GitHub secrets

name: GCP Streamlit App Deployment

on:
  pull_request:
    branches: [ main ]
    paths:
      - src/ner_streamlit_app/**

jobs:

    deploy:
        # Authenticate to GCP
        name: Setup Gcloud Account
        runs-on: ubuntu-latest
        env:
          IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }}
        steps:

        # Set GCP credentials in CI/CD instance
        - name: Login
          uses: google-github-actions/setup-gcloud@v0
          with:
            project_id: ${{ secrets.GCP_PROJECT_ID }}
            service_account_email: ${{ secrets.GCP_EMAIL }}
            service_account_key: ${{ secrets.GCP_CREDENTIALS }}

        # Allow CI/CD instance to use Docker in GCP
        - name: Configure Docker
          run: gcloud auth configure-docker --quiet

        # Checkout repository in GCP
        - name: Checkout repository
          uses: actions/checkout@v2

        # Run cloudbuild.yaml in the correct directory
        - name: Run Cloud Build process
          run: gcloud builds submit --config cloudbuild.yaml
          working-directory: src/ner_streamlit_app
