# Secrets defined in GitHub secrets

name: GCP Streamlit App Deployment

on:
  pull_request:
    branches: [ main ]
    paths:
      - src/ner_streamlit_app/**

jobs:
    deploy-streamlit-app:
        # Authenticate to GCP
        name: Setup Gcloud Account
        runs-on: ubuntu-latest
        # Add "id-token" with the intended permissions.
        permissions:
          contents: 'read'
          id-token: 'write'
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v3
        - id: 'auth'
          uses: 'google-github-actions/auth@v1'
          with:
            workload_identity_provider: ${{ secrets.GCP_GITHUB_WORKLOAD_IDENTITY_PROVIDER }}
            service_account: ${{ secrets.GCP_NER_APP_SA }}
        # `setup-gcloud` automatically picks up authentication from `auth`
        - name: 'Set up gcloud'
          uses: 'google-github-actions/setup-gcloud@v1'

        # ASet up docker to authenticate
        - name: Configure Docker
          run: gcloud auth configure-docker europe-west2-docker.pkg.dev --quiet

        # Run cloudbuild.yaml in the correct directory
        - name: Run Cloud Build Process
          run: gcloud builds submit --config cloudbuild.yaml
          working-directory: src/ner_streamlit_app

        # Deploy container image to Cloud Run
        - name: Deploy to Cloud Run
          id: 'deploy'
          uses: 'google-github-actions/deploy-cloudrun@v1'
          with:
            service: 'ner-streamlit-app'
            image: 'europe-west2-docker.pkg.dev/cpto-content-metadata/cpto-content-metadata-docker-repo/ner-streamlit-app'
            flags: '--region=europe-west2 --port=8501 --min-instances=0 --max-instances=5 --cpu=1 --memory=4Gi'
