name: Upload JSON request body file to Google Storage

# Upload JSON when changes to the file have been pushed to GitHub
# Ref: https://github.com/google-github-actions/upload-cloud-storage#upload-cloud-storage
# and https://github.com/tj-actions/changed-files
on:
  push:
    paths:
      - inference_pipeline_new_content/json_files/request_daily_ner.json
env:
  PATH_TO_FILE: inference_pipeline_new_content/json_files/request_daily_ner.json
  DESTINATION_BUCKET_NAME: cpto-content-metadata/vertex_ner_daily_batchjob

jobs:
    upload-json-to-gs:
        # Authenticate to GCP
        name: Setup Gcloud Account
        runs-on: ubuntu-latest
        # Add "id-token" with the intended permissions.
        permissions:
          contents: 'read'
          id-token: 'write'
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - id: 'auth'
          uses: 'google-github-actions/auth@v1'
          with:
            workload_identity_provider: ${{ secrets.GCP_GITHUB_WORKLOAD_IDENTITY_PROVIDER }}
            service_account: ${{ secrets.GCP_NER_NEW_CONTENT_PIPE_SA }}
        # Install gcloud, `setup-gcloud` automatically picks up authentication from `auth`.
        - name: 'Set up Cloud SDK'
          uses: 'google-github-actions/setup-gcloud@v1'
        - id: 'upload-file'
          uses: 'google-github-actions/upload-cloud-storage@v1'
          with:
            path: ${{ env.PATH_TO_FILE }}
            destination: ${{ env.DESTINATION_BUCKET_NAME }}
